language: ruby
branches:
  only:
  - master
rvm:
- 2.1.2
install:
- git config --global user.email "github_bot@segiddins.me"
- git config --global user.name "GiddinsBot"
- sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-latex-base
- rake bootstrap
script:
- git remote set-url origin "https://${GH_TOKEN}@github.com/segiddins/resume.segiddins.me.git"
- bundle exec rake deploy
env:
  global:
    secure: NHmJOiKgcPkZw/Y3V6p6pqA/2sb02GGLbI10ZgYWaaNs9MHEeYlNoN1KlJqtDgQGsiE2IHGMMTAXhDYzXYyRuc9LHgYsi9Rp4kr0qamLxQAmUZmjvcN/i7Va/DZkE0h9ISGzHTD1vf2/wXroQ0ZdUPtBaurGYH+h0YJm4MwVbGk=
